services:
  todo-webapp:
    build: ./todo-webapp
    image: "todo-webapp:release-3.1"
    container_name: todo-webapp
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - api-gateway

  todo-service:
    build: ./todo
    image: "todo:release-3"
    container_name: todo-service
    environment:
      REDIS_HOST: redis
    networks:
      - todo-net
    expose:
      - 8000
    depends_on:
      - redis

  notification-service:
    build: ./todo-notification
    image: "todo-notification:release-1.1"
    container_name: notification-service
    environment:
      REDIS_HOST: redis
    networks:
      - todo-net
    expose:
      - 9000
    depends_on:
      - redis

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - todo-net
    depends_on:
      - todo-service
      - notification-service

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge